version: '2'
services:
    db:
        image: postgres
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DATABASE: ${POSTGRES_INFO}
            POSTGRES_USER: ${POSTGRES_INFO}
            POSTGRES_PASSWORD: ${POSTGRES_INFO}
    php:
        build: ./php-fpm
        expose:
            - "9000"
        ports:
            - "9001:9000"
        volumes:
            - ..:/var/www/app
        links:
            - db
    nginx:
        build: ./nginx
        ports:
            - "80:80"
        links:
            - php
        volumes_from:
            - php
        volumes:
            - ../logs/:/var/log/nginx
